name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - release/**
      - feature/**
      - hotfix/**

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Unit tests
        run: npm test -- --ci
      - name: E2E tests
        run: npm run test:e2e