name: Deploy Develop to Render

on:
    push:
        branches:
            - develop

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Deploy to Render (develop/staging)
              run: |
                  curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
